### ISSUE TITLE
i18n 페이지마다 실제 적용

### ISSUE THREAD

**Issue by Fibo4487** [studying-ice-bear/mintBear#3]
i18n 언어 선택하면 페이지의 언어가 바로 바뀔수 있도록 적용

**Comment by PrettyHan** [comment]
페이지 언어 바뀔때 한국어 / 영어 / 일본어로 할거?? <난 일본어는 있었음 좋겟음>
번역문 필요한가??

**Comment by Fibo4487** [comment]
deepl로 돌려서 넣으려고 했어서 번역문 대신에 검수해주면 좋을거 같음
